spring:
  data:
    redis:
      host: localhost
      password: 123456
      database: 1

  # 数据库相关配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/pig?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true&nullCatalogMeansCurrent=true

# 本地文件系统
file:
  local:
    enable: true
    base-path: E:/智慧停车系统/images/img

## 登录配置
security:
  # 登录报文加密根密钥 ，必须是16位
  encodeKey: thanks,pig4cloud
  # 跳过验证码校验的客户端
  ignore-clients:
    - test

# 配置文件加密根密码
jasypt:
  encryptor:
    password: pig
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator

# swagger 配置
swagger:
  token-url: ${swagger.gateway}/admin/oauth2/token
